from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

class DecisionMakingAgent:
    def __init__(self):
        print("Loading SLM (google/flan-t5-base)...")
        self.tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
        self.model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")
        print("SLM Loaded.")

    def make_decision(self, patient_history, knowledge_summary, causal_dag, clinician_comment=None):
        """
        Combines inputs to make a final prediction and explanation using Flan-T5.
        """
        
        predictions = causal_dag.get("predictions", [])
        
        if not predictions:
            return {
                "final_prediction": None,
                "explanation": "No clear risk identified based on current history.",
                "recommendations": []
            }
            
        # Select the highest probability disease
        top_prediction = predictions[0]
        disease_code = top_prediction['disease_code']
        probability = top_prediction['probability']
        
        # Prepare Prompt
        history_str = f"Patient history ends with {patient_history[-1]['disease_code']}."
        knowledge_str = knowledge_summary.get("summary", "")[:300] # Truncate for token limit
        
        prompt = (
            f"Explain why the patient is at risk of {disease_code} ({probability*100:.0f}% chance). "
            f"Context: {history_str} "
            f"Medical Knowledge: {knowledge_str} "
        )
        
        if clinician_comment:
            prompt += f" Clinician Note: {clinician_comment}"
            
        prompt += " Explanation:"

        # Generate Output
        inputs = self.tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)
        outputs = self.model.generate(**inputs, max_length=150, num_beams=4, early_stopping=True)
        generated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        # Generate actionable recommendations
        recommendations = self._generate_recommendations(
            patient_history[-1]['disease_code'],
            disease_code,
            probability
        )
        
        # Format the final report
        explanation = (
            f"DECISION AGENT REPORT (Generated by Flan-T5):\n"
            f"1. Analysis of History: {history_str}\n"
            f"2. Causal Discovery: Identified {disease_code} as the most likely progression.\n"
            f"3. SLM Insight: {generated_text}\n"
            f"4. Risk Level: {'HIGH' if probability > 0.5 else 'MODERATE' if probability > 0.3 else 'LOW'} ({probability*100:.0f}%)"
        )
            
        return {
            "final_prediction": top_prediction,
            "explanation": explanation,
            "recommendations": recommendations
        }
    
    def _generate_recommendations(self, current_disease, predicted_disease, probability):
        """Generate actionable clinical recommendations."""
        recommendations = []
        
        # Risk-based recommendations
        if probability > 0.5:
            recommendations.append({
                "priority": "HIGH",
                "action": "Schedule follow-up within 1-2 weeks",
                "rationale": f"High risk ({probability*100:.0f}%) of progression to {predicted_disease}"
            })
        elif probability > 0.3:
            recommendations.append({
                "priority": "MEDIUM",
                "action": "Schedule follow-up within 1 month",
                "rationale": f"Moderate risk ({probability*100:.0f}%) of progression"
            })
        
        # Disease-specific recommendations
        disease_recommendations = {
            "I50.9": [
                {"action": "Monitor fluid intake/output daily", "type": "monitoring"},
                {"action": "Prescribe ACE inhibitor if not contraindicated", "type": "medication"},
                {"action": "Restrict sodium to <2g/day", "type": "lifestyle"}
            ],
            "E11": [
                {"action": "Check HbA1c every 3 months", "type": "monitoring"},
                {"action": "Initiate metformin therapy", "type": "medication"},
                {"action": "Refer to diabetes education program", "type": "education"}
            ],
            "N18.9": [
                {"action": "Monitor creatinine and eGFR monthly", "type": "monitoring"},
                {"action": "Adjust medications for renal function", "type": "medication"},
                {"action": "Limit protein intake to 0.8g/kg/day", "type": "lifestyle"}
            ]
        }
        
        if predicted_disease in disease_recommendations:
            for rec in disease_recommendations[predicted_disease]:
                recommendations.append({
                    "priority": "STANDARD",
                    "action": rec["action"],
                    "type": rec["type"]
                })
        
        return recommendations
